language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.7

env:
  matrix:
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=clang
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=clang
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release PRJ_COMPILER=gcc
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug PRJ_COMPILER=gcc
  - TEST_SUITE=benchmark

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - memcached
      - libmemcached6

before_install:
  - pip install --upgrade pip

install:
  # install python deps
  - pip install Cython
  - if [ $TEST_SUITE = "unittest" ]; then pip install pytest greenify gevent numpy; fi
  - if [ $TEST_SUITE = "benchmark" ]; then pip install git+https://github.com/lericson/pylibmc@master#egg=pylibmc; fi
  - if [ $TEST_SUITE = "benchmark" ]; then pip install git+https://github.com/linsomniac/python-memcached.git@master#egg=memcache; fi

before_script:
  - ./misc/memcached_server start

script:
  - if [ $PRJ_COMPILER = "gcc" ]; then export CC=gcc CXX=g++; fi
  - if [ $PRJ_COMPILER = "clang" ]; then export CC=clang CXX=clang++; fi
  - ./misc/travis/$TEST_SUITE.sh

after_script:
  - ./misc/memcached_server stop
