dist: xenial

language: python
python:
  - "2.7"
  - "3.5"

cache:
  pip: true

compiler:
  - clang
  - gcc

env:
  - TEST_SUITE=cppcheck
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Release
  - TEST_SUITE=unittest CMAKE_BUILD_TYPE=Debug
  - TEST_SUITE=benchmark

matrix:
  exclude:
  - env: TEST_SUITE=cppcheck
    compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python-dev
      - python-numpy
      - valgrind
      - cppcheck
      - memcached
      - libmemcached10
      - golang
      - g++-7

install:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TEST_SUITE != "cppcheck" ]]; then pip install future; fi
  - if [[ $TEST_SUITE = "unittest" ]]; then pip install pytest greenify gevent; fi
  - if [[ $TEST_SUITE = "benchmark" ]]; then pip install python-memcached pylibmc; fi

before_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server start; fi

script:
  - if [[ $CC = "gcc" ]]; then export CC=gcc-7 CXX=g++-7; fi
  - ./misc/travis/$TEST_SUITE.sh

after_script:
  - if [[ $TEST_SUITE != "cppcheck" ]]; then ./misc/memcached_server stop; fi

deploy:
  provider: pypi
  skip_existing: true
  user: yangxiufeng
  password:
    secure: Oc2qdGCFGP5W51RcdD25q0hJx1mUOWf65ph8/T7hW2N4bjz2TJPsLvf37MNi5aHum0Kvqxo6HNEn3Ea+nqL9KgjxhnjmqSezwqxpXJrHgnqPMAH7prfpPpJW9R0h3PJDutMNmhsL2xn9NJeb6LQ+y38j44n1pN2JW3t2Z3CJavA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: douban/libmc
    branch: master
